package it.simonesalvo.hangman.common;

/**
 * Created by Simone Salvo on 26/06/15.
 * www.simonesalvo.it
 */

public enum MessageType {
    OPEN_GAME, JOIN_GAME, START_GAME, CLOSE_GAME, INITILIAZZATION_ACK, EXCEDED_GAME, UPDATE_STATUS, PROPOSAL, GAME_NOT_EXIST, EXIT, GAME_LEAVING, UPDATE_STATUS_CHAR_KO, UPDATE_STATUS_CHAR_OK, GAME_COMPLETED, NO_MORE_GAME_ATTEMPS, INVALID_CHARACTER, UNJOIN_GAME, LOGOUT, GAME_ANNULLED, MULTICAST_EXISTING;

}
